# -*- coding: utf-8 -*-
"""add.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lfIcqZyrdGi6OoAtskPPd2HTjTZvrIN2
"""

def add(x,y):
    return x+y

